Update Update.yml

diff --git a/.github/workflows/Update.yml b/.github/workflows/Update.yml
--- a/.github/workflows/Update.yml
+++ b/.github/workflows/Update.yml
@@ -16,19 +16,19 @@ jobs:
       uses: actions/checkout@v4
 
     - name: GetTime
-      run: echo "GET_TIME=$(date +'%Y-%m-%d %H:%M:%S CST')" >> $GITHUB_ENV
+      run: echo "GET_TIME=$(date +'%Y-%m-%d %H:%M:%S CST')" >> $GITHUB_ENV  
 
     - name: Update
       run: |
         # 央视源
-        rm -f CCTV.m3u && wget https://m3u.ibert.me/fmml_dv6.m3u -O CCTV.m3u
-        if [ ! -f "CCTV.m3u" ]; then
-          echo "Failed to download CCTV.m3u"
-          exit 1
-        fi
-        sed -i -n '/央视/,+1p' CCTV.m3u
-        sed -i '1i #EXTM3U' CCTV.m3u
-        sed -i '/^\s*$/d' CCTV.m3u
+        # rm -f CCTV.m3u && wget https://m3u.ibert.me/fmml_dv6.m3u -O CCTV.m3u  
+        # if [ ! -f "CCTV.m3u" ]; then
+        #   echo "Failed to download CCTV.m3u"
+        #   exit 1
+        # fi
+        # sed -i -n '/央视/,+1p' CCTV.m3u
+        # sed -i '1i #EXTM3U' CCTV.m3u
+        # sed -i '/^\s*$/d' CCTV.m3u
         # 添加额外的央视源
         rm -f CCTV1.m3u && wget https://m3u.ibert.me/fmml_ipv6.m3u -O CCTV1.m3u
         if [ ! -f "CCTV1.m3u" ]; then
@@ -36,14 +36,14 @@ jobs:
           exit 1
         fi
         sed -i -n '/央视/,+1p' CCTV1.m3u
-        sed -i '1i #EXTM3U' CCTV1.m3u
+        sed -i '1i #EXTM3U' CCTV1.m3u  
         sed -i '/^\s*$/d' CCTV1.m3u
-        cat CCTV1.m3u >> CCTV.m3u
+        cat CCTV1.m3u >> CCTV.m3u  
         rm -f CCTV1.m3u
         # 卫视源
         rm -f CNTV.m3u && touch CNTV.m3u
         # 下载并处理CNTV1.m3u（卫视）
-        wget https://m3u.ibert.me/fmml_dv6.m3u -O CNTV1.m3u
+        wget https://m3u.ibert.me/fmml_ipv6.m3u -O CNTV1.m3u
         if [ ! -f "CNTV1.m3u" ]; then
           echo "Failed to download CNTV1.m3u"
           exit 1
@@ -65,7 +65,7 @@ jobs:
         cat CNTV2.m3u >> CNTV.m3u
         rm -f CNTV2.m3u
         # 下载并处理CNTV3.m3u（百视）
-        wget https://m3u.ibert.me/fmml_dv6.m3u -O CNTV3.m3u
+        wget https://m3u.ibert.me/fmml_ipv6.m3u -O CNTV3.m3u
         if [ ! -f "CNTV3.m3u" ]; then
           echo "Failed to download CNTV3.m3u"
           exit 1
